import { useRef, useState } from 'react'
import GoalManager from '../components/GoalManager'
import Mascot from '../components/Mascot'
import ReportPanel from '../components/ReportPanel'
import ReminderSettings from '../components/ReminderSettings'
import DataManager from '../components/DataManager'
import BackButton from '../components/BackButton'
import FootprintIcon from '../components/FootprintIcon'
import { distance, inclusiveDaysSince } from '../lib/product'
import { AVATAR_OPTIONS, isAvatarSelection, profileAvatarSrc } from '../lib/profileAvatar'

export default function Profile({profile,totalMeters,theme,setTheme,setProfile,history,legacySpecial,weeklySpecials,completionLog,now,reminders,setReminders,restartOnboarding,resetAll,view,setView,actualDiscoveries=[]}) {
 const [name,setName]=useState(profile.name),[avatar,setAvatar]=useState(profile.avatar),[photoError,setPhotoError]=useState(''); const photoInput=useRef(null); const back=()=>window.history.back(); const togetherDays=inclusiveDaysSince(profile.journeyStartedAt,now)
 const choosePhoto=async e=>{const file=e.target.files?.[0];e.target.value='';if(!file||!file.type.startsWith('image/'))return setPhotoError('이미지 파일을 선택해주세요.');try{const bitmap=await createImageBitmap(file),size=Math.min(bitmap.width,bitmap.height),canvas=document.createElement('canvas');canvas.width=canvas.height=512;canvas.getContext('2d').drawImage(bitmap,(bitmap.width-size)/2,(bitmap.height-size)/2,size,size,0,0,512,512);bitmap.close?.();setAvatar({type:'photo',value:canvas.toDataURL('image/jpeg',.82)});setPhotoError('')}catch{setPhotoError('사진을 불러오지 못했어요. 다른 사진을 선택해주세요.')}}
 const save=()=>{const next=name.trim();if(!next)return;setProfile({...profile,name:next,avatar});back()}
 if(view==='goals')return <main className="screen profile-screen"><GoalManager profile={profile} save={n=>{setProfile(n);back()}} cancel={back}/></main>
 if(view==='report')return <main className="screen profile-screen"><ReportPanel records={completionLog} history={history} legacySpecial={legacySpecial} weeklySpecials={weeklySpecials} now={now} onBack={back}/></main>
 if(view==='reminders')return <main className="screen profile-screen"><ReminderSettings reminders={reminders} setReminders={setReminders} onBack={back}/></main>
 if(view==='data')return <main className="screen profile-screen"><DataManager onBack={back} onGoals={()=>setView('goals')} onOnboarding={restartOnboarding} onResetAll={resetAll}/></main>
 if(view==='edit')return <main className="screen profile-screen"><section className="profile-head sub-head"><BackButton onClick={back}/><h1>프로필 편집</h1></section><section className="screen-content avatar-settings"><div className="avatar-preview"><img src={profileAvatarSrc(avatar)} alt="프로필 미리보기"/></div><div className="avatar-grid" aria-label="기본 아바타 선택">{AVATAR_OPTIONS.map(a=>{const selected=isAvatarSelection(avatar)&&avatar.id===a.id;return <button key={a.id} className={`avatar-option ${selected?'selected':''}`} aria-pressed={selected} onClick={()=>setAvatar({type:'avatar',id:a.id})}><img src={`${import.meta.env.BASE_URL}art/${a.id}.png`} alt={a.label}/>{selected&&<span>✓</span>}</button>})}</div><button className="avatar-choice" onClick={()=>photoInput.current?.click()}><span>🖼️</span><b>휴대폰 사진에서 선택</b></button><input ref={photoInput} hidden type="file" accept="image/*" onChange={choosePhoto}/>{photoError&&<p className="avatar-error">{photoError}</p>}<label className="profile-edit-name">이름<input value={name} onChange={e=>setName(e.target.value)} aria-label="이름"/></label><button className="profile-edit-save" onClick={save}>저장</button></section></main>
 return <main className="screen profile-screen"><section className="profile-head"><h1>마이페이지</h1></section><section className="screen-content"><div className="profile-identity"><div className="profile-avatar"><img src={profileAvatarSrc(profile.avatar)} alt=""/></div><div className="profile-copy"><h2>{profile.name}님</h2><p>나만의 속도로, 꾸준히 🌱</p></div><button className="edit-btn" aria-label="프로필 편집" onClick={()=>{setName(profile.name);setAvatar(profile.avatar);setView('edit')}}>✎</button></div><div className="profile-stats"><div><FootprintIcon/><b className="profile-stage-name">{actualDiscoveries.length}곳</b><small>발견한 발자취</small></div><div><span>🌱</span><b className="journey-distance-stat">{distance(totalMeters)}</b><small>지금까지의 여정</small></div><div><span>🗓️</span><b>{togetherDays}일</b><small>함께한 날</small></div></div><div className="settings-card"><button className="settings-row" onClick={()=>setView('goals')}><i>🎯</i><span>내 목표</span><b>›</b></button><button className="settings-row" onClick={()=>setView('report')}><i>📊</i><span>통계 리포트</span><b>›</b></button><button className="settings-row" onClick={()=>setView('reminders')}><i>🔔</i><span>리마인더 설정</span><b>›</b></button><div className="settings-row theme-row"><i>🎨</i><span>테마 설정</span><select aria-label="테마 설정" value={theme} onChange={e=>setTheme(e.target.value)}><option value="auto">자동</option><option value="light">라이트</option><option value="dark">다크</option></select></div><button className="settings-row" onClick={()=>setView('data')}><i>💾</i><span>데이터 관리</span><b>›</b></button></div><div className="profile-landscape"><div className="profile-rest-slogan"><b>Better</b><b>Than</b><b>Yesterday</b><span>♡</span></div><div className="profile-rest-copy"><b>충분히<br/>쉬는 것도<br/>중요해요.</b><span>♡</span></div><div className="profile-sleep-mascot"><Mascot mood="sleep" size="sm" className="sleep-character-wrap"/></div></div></section></main>
}
