import FootprintIcon from './FootprintIcon'
const collectionArt = {
  'first-step': 'collection-001-first-step.png',
  'statue-liberty': 'collection-002-statue-of-liberty.png',
  hyperion: 'collection-003-hyperion.png',
  seongsan: 'collection-004-seongsan-ilchulbong.png',
  'building-63': 'collection-005-63-building.png',
  titanic: 'collection-006-titanic.png',
  eiffel: 'collection-007-eiffel-tower.png',
  track: 'collection-008-track-lap.png',
  lotte: 'collection-009-lotte-world-tower.png',
  'tokyo-skytree': 'collection-010-tokyo-skytree.png',
  'burj-khalifa': 'collection-011-burj-khalifa.png',
  baegundae: 'collection-012-bukhansan-baegundae.png',
  'first-1km': 'collection-013-first-1k.png',
  'sydney-harbour': 'collection-014-sydney-harbour-bridge.png',
  'meteor-crater': 'collection-015-meteor-crater.png',
  haeundae: 'collection-016-haeundae.png',
  seoraksan: 'collection-017-daecheongbong.png',
  hallasan: 'collection-018-hallasan.png',
  seokchon: 'collection-019-seokchon-lake.png',
  'golden-gate': 'collection-020-golden-gate-bridge.png',
  'jeongdong-simgok': 'collection-021-jeongdong-simgok-badabuchaegil.png',
  'monaco-f1': 'collection-022-monaco-f1-circuit.png',
  'marina-bay': 'collection-023-marina-bay.png',
  gyeongpo: 'collection-024-gyeongpo-lake.png',
  'first-5km': 'collection-025-first-5k.png',
  hwaseong: 'collection-026-suwon-hwaseong.png',
  gwanggyo: 'collection-027-gwanggyo-lake-park.png',
  manjanggul: 'collection-028-manjanggul.png',
  everest: 'collection-029-everest.png',
  'first-10km': 'collection-030-first-10k.png',
  'challenger-deep': 'collection-031-challenger-deep.png',
  saryeoni: 'collection-032-saryeoni-forest-path.png',
  'grand-canyon': 'collection-033-grand-canyon.png',
  hanyang: 'collection-034-hanyangdoseong.png',
  half: 'collection-035-half-marathon.png',
  incheon: 'collection-036-incheon-bridge.png',
  'yeosu-goheung': 'collection-037-baekri-seomseom-gil.png',
  'perito-moreno': 'collection-038-perito-moreno.png',
  saemangeum: 'collection-039-saemangeum-seawall.png',
  marathon: 'collection-040-marathon.png',
  'marado-lighthouse': 'collection-041-marado-lighthouse-light.png',
  yulhyeon: 'collection-042-yulhyeon-tunnel.png',
  'bukhangang-cycle': 'collection-043-bukhangang-bike-path.png',
  'panama-canal': 'collection-044-panama-canal.png',
  dokdo: 'collection-045-dokdo.png',
}

export default function MilestoneIcon({ milestone }) {
  const asset = collectionArt[milestone.id]
  if (asset) return <img className="collection-art" src={`${import.meta.env.BASE_URL}art/collections/${asset}`} alt="" />
  return milestone.id === 'first-step' ? <FootprintIcon /> : milestone.icon
}
