import FootprintIcon from './FootprintIcon'
const collectionArt = {
  'first-step': 'collection-001-first-step.png',
  'statue-liberty': 'collection-002-statue-of-liberty.png',
  hyperion: 'collection-003-hyperion.png',
  seongsan: 'collection-004-seongsan-ilchulbong.png',
  'building-63': 'collection-005-63-building.png',
  titanic: 'collection-006-titanic.png',
  eiffel: 'collection-007-eiffel-tower.png',
  track: 'collection-008-track-lap.png',
  lotte: 'collection-009-lotte-world-tower.png',
  'tokyo-skytree': 'collection-010-tokyo-skytree.png',
  'burj-khalifa': 'collection-011-burj-khalifa.png',
  baegundae: 'collection-012-bukhansan-baegundae.png',
  'first-1km': 'collection-013-first-1k.png',
  'sydney-harbour': 'collection-014-sydney-harbour-bridge.png',
  'meteor-crater': 'collection-015-meteor-crater.png',
  haeundae: 'collection-016-haeundae.png',
  seoraksan: 'collection-017-daecheongbong.png',
  hallasan: 'collection-018-hallasan.png',
  seokchon: 'collection-019-seokchon-lake.png',
  'golden-gate': 'collection-020-golden-gate-bridge.png',
  'jeongdong-simgok': 'collection-021-jeongdong-simgok-badabuchaegil.png',
  'monaco-f1': 'collection-022-monaco-f1-circuit.png',
  'marina-bay': 'collection-023-marina-bay.png',
  gyeongpo: 'collection-024-gyeongpo-lake.png',
  'first-5km': 'collection-025-first-5k.png',
  hwaseong: 'collection-026-suwon-hwaseong.png',
  gwanggyo: 'collection-027-gwanggyo-lake-park.png',
  manjanggul: 'collection-028-manjanggul.png',
  everest: 'collection-029-everest.png',
  'first-10km': 'collection-030-first-10k.png',
  'challenger-deep': 'collection-031-challenger-deep.png',
  saryeoni: 'collection-032-saryeoni-forest-path.png',
  'grand-canyon': 'collection-033-grand-canyon.png',
  hanyang: 'collection-034-hanyangdoseong.png',
  half: 'collection-035-half-marathon.png',
  incheon: 'collection-036-incheon-bridge.png',
  'yeosu-goheung': 'collection-037-baekri-seomseom-gil.png',
  'perito-moreno': 'collection-038-perito-moreno.png',
  saemangeum: 'collection-039-saemangeum-seawall.png',
  marathon: 'collection-040-marathon.png',
  'marado-lighthouse': 'collection-041-marado-lighthouse-light.png',
  yulhyeon: 'collection-042-yulhyeon-tunnel.png',
  'bukhangang-cycle': 'collection-043-bukhangang-bike-path.png',
  'panama-canal': 'collection-044-panama-canal.png',
  dokdo: 'collection-045-dokdo.png',
}

// Presentation-only normalization: transparent canvases vary by Collection,
// while distance and discovery data remain entirely in milestonesV2.
const displayScale = {
  'first-step': 1.18, 'statue-liberty': 1.14, hyperion: 1.26, seongsan: 1.14,
  titanic: 1.2, eiffel: 1.22, track: 1.1, lotte: 1.2, 'tokyo-skytree': 1.2,
  'burj-khalifa': 1.2, baegundae: 1.14, 'first-1km': 1.24,
  'sydney-harbour': 1.18, 'meteor-crater': 1.16, haeundae: 1.16,
  seoraksan: 1.15, hallasan: 1.15, seokchon: 1.14, 'golden-gate': 1.18,
  'jeongdong-simgok': 1.16, 'monaco-f1': 1.17, 'marina-bay': 1.14,
  gyeongpo: 1.14, 'first-5km': 1.24, hwaseong: 1.15, gwanggyo: 1.14,
  manjanggul: 1.16, everest: 1.15, 'first-10km': 1.24,
  'challenger-deep': 1.15, saryeoni: 1.18, 'grand-canyon': 1.16,
  hanyang: 1.16, half: 1.24, incheon: 1.18, 'yeosu-goheung': 1.18,
  'perito-moreno': 1.15, saemangeum: 1.18, marathon: 1.24,
  'marado-lighthouse': 1.17, yulhyeon: 1.17, 'bukhangang-cycle': 1.18,
  'panama-canal': 1.18, dokdo: 1.16,
}

export default function MilestoneIcon({ milestone }) {
  const asset = collectionArt[milestone.id]
  if (asset) return <span className="collection-art-frame" style={{ '--collection-art-scale': displayScale[milestone.id] || 1.16 }}><img className="collection-art" src={`${import.meta.env.BASE_URL}art/collections/${asset}`} alt="" /></span>
  return milestone.id === 'first-step' ? <FootprintIcon /> : milestone.icon
}
