import { useEffect, useMemo, useState } from 'react'
import './App.css'

const DEFAULT_QUESTS=[
{id:'tidy',title:'내 몫 정리',category:'LIFE',xp:10,icon:'🧹'},
{id:'workout',title:'운동하기',category:'BODY',xp:10,icon:'🏃'},
{id:'english',title:'영어 공부 10분 이상',category:'GROWTH',xp:10,icon:'💬'},
{id:'reading',title:'독서하기 5페이지 이상',category:'GROWTH',xp:10,icon:'📖'},
{id:'house',title:'집안일 오늘 하나는 꼭',category:'LIFE',xp:10,icon:'🏠'}]
const SPECIALS=[
{id:'dust',title:'숨어있는 먼지를 찾아라',description:'평소 잘 닦지 않는 곳 한 군데의 먼지를 닦아보세요.',xp:20,icon:'✨'},
{id:'reset',title:'10분 리셋',description:'타이머 10분을 켜고 눈에 보이는 공간 하나를 정리해보세요.',xp:20,icon:'⏱️'},
{id:'walk',title:'한 정거장 더',description:'오늘은 평소보다 15분 더 걸어보세요.',xp:20,icon:'🥾'},
{id:'message',title:'마음 한 줄 보내기',description:'고마운 사람에게 짧은 안부나 감사 메시지를 보내보세요.',xp:20,icon:'💌'}]
const CATEGORIES=['LIFE','BODY','GROWTH','RELATIONSHIP','WORK','HOBBY']
const localDateKey=(d=new Date())=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`
const addDays=(d,n)=>{const x=new Date(d);x.setDate(x.getDate()+n);return x}
const weekKey=(d=new Date())=>{const x=new Date(d);const day=(x.getDay()+6)%7;x.setDate(x.getDate()-day);return localDateKey(x)}
const safeParse=(v,f)=>{try{return v?JSON.parse(v):f}catch{return f}}

function Mascot({mood='basic',small=false}){return <div className={`mascot ${small?'small':''} ${mood}`}><i className="sprout">♧</i><div className="mascot-body"><span className="eye e1"/><span className="eye e2"/><span className="mouth">⌣</span><span className="cheek c1"/><span className="cheek c2"/></div></div>}
function Logo(){return <div className="logo">My Pace <span>●</span></div>}
function App(){
 const [now,setNow]=useState(new Date()),todayKey=localDateKey(now),thisWeek=weekKey(now)
 const [tab,setTab]=useState('today');const [quests,setQuests]=useState(()=>safeParse(localStorage.getItem('myPaceQuestDefinitions'),DEFAULT_QUESTS));const [history,setHistory]=useState(()=>safeParse(localStorage.getItem('myPaceHistory'),{}));const [specialHistory,setSpecialHistory]=useState(()=>safeParse(localStorage.getItem('myPaceSpecialHistory'),{}))
 useEffect(()=>{const id=setInterval(()=>setNow(new Date()),60000);return()=>clearInterval(id)},[]);useEffect(()=>localStorage.setItem('myPaceHistory',JSON.stringify(history)),[history]);useEffect(()=>localStorage.setItem('myPaceSpecialHistory',JSON.stringify(specialHistory)),[specialHistory]);useEffect(()=>localStorage.setItem('myPaceQuestDefinitions',JSON.stringify(quests)),[quests])
 const todayCompleted=history[todayKey]?.completed||{},completedCount=quests.filter(q=>todayCompleted[q.id]).length
 const special=SPECIALS[Math.abs([...thisWeek].reduce((a,c)=>a+c.charCodeAt(0),0))%SPECIALS.length],specialDone=specialHistory[thisWeek]?.completed===true
 const stats=useMemo(()=>{const days=Array.from({length:28},(_,i)=>localDateKey(addDays(now,-27+i)));let total=0,done=0;days.forEach(k=>{if(!history[k])return;quests.forEach(q=>{total++;if(history[k]?.completed?.[q.id])done++})});return{score:total?Math.round(done/total*100):Math.round(completedCount/Math.max(quests.length,1)*100),days}},[history,quests,now,completedCount])
 const totalXP=useMemo(()=>{let xp=720;Object.values(history).forEach(r=>quests.forEach(q=>{if(r.completed?.[q.id])xp+=q.xp||10}));Object.values(specialHistory).forEach(r=>{if(r.completed)xp+=r.xp||20});return xp},[history,quests,specialHistory]);const level=Math.floor(totalXP/100)
 const toggleQuest=id=>setHistory(p=>({...p,[todayKey]:{...(p[todayKey]||{}),completed:{...(p[todayKey]?.completed||{}),[id]:!todayCompleted[id]}}}));const toggleSpecial=()=>setSpecialHistory(p=>({...p,[thisWeek]:{completed:!specialDone,xp:special.xp,id:special.id}}))
 const addQuest=()=>{if(quests.length>=5)return alert('Daily Quest는 최대 5개까지 설정할 수 있어요.');const title=prompt('새 Daily Quest 이름을 입력하세요.');if(title?.trim())setQuests(p=>[...p,{id:`q-${Date.now()}`,title:title.trim(),category:'LIFE',xp:10,icon:'🌱'}])};const removeQuest=id=>{if(quests.length<=3)return alert('Daily Quest는 최소 3개가 필요해요.');setQuests(p=>p.filter(q=>q.id!==id))}
 return <div className="app-shell"><div className="phone-frame">{tab==='today'?<Home {...{now,stats,quests,todayCompleted,completedCount,toggleQuest,totalXP,level}}/>:tab==='quests'?<Quests {...{quests,todayCompleted,toggleQuest,addQuest}}/>:tab==='pace'?<Pace {...{now,stats,history,quests,totalXP}}/>:tab==='special'?<Special {...{special,specialDone,toggleSpecial}}/>:<Profile {...{quests,addQuest,removeQuest,totalXP,level}}/>}<Nav tab={tab} setTab={setTab}/></div></div>
}
function Home({now,stats,quests,todayCompleted,completedCount,toggleQuest,totalXP,level}){const pct=Math.round(completedCount/quests.length*100);return <main className="page home"><header className="brand-row"><Logo/><span className="mini-avatar"><Mascot small/></span></header><section className="hello"><div><b>안녕, 승호님!</b><p>오늘도 너의 속도로 가고 있어요! 💚</p></div></section><section className="landscape"><div className="cloud one"/><div className="cloud two"/><div className="mountain m1"/><div className="mountain m2"/><div className="speech">조금씩, 잘하고 있어!</div><Mascot/><div className="grass"/></section><section className="progress-card"><span>오늘의 진행도</span><div className="progress-title"><b>{completedCount} / {quests.length} 완료</b><strong>{pct}%</strong></div><div className="green-progress"><i style={{width:`${pct}%`}}/></div></section><section className="stats-three"><div><span>🔥</span><b>{Math.max(1,Math.round(stats.score/10))}</b><small>나의 페이스</small></div><div><span>👑</span><b>{totalXP}</b><small>Total XP</small></div><div><span>🌿</span><b>{level}</b><small>레벨</small></div></section><section className="quick-quests"><div className="section-heading"><h2>오늘의 퀘스트</h2><span>{now.getMonth()+1}월 {now.getDate()}일</span></div>{quests.slice(0,3).map(q=><button key={q.id} className={todayCompleted[q.id]?'done':''} onClick={()=>toggleQuest(q.id)}><i>{q.icon||'🌱'}</i><span><b>{q.title}</b><small>{q.category}</small></span><em>{todayCompleted[q.id]?'✓':'○'}</em></button>)}</section><p className="quote">“작은 실천이 오늘도 더 좋은 나를 만들어요.”</p></main>}
function Quests({quests,todayCompleted,toggleQuest,addQuest}){return <main className="page"><PageHead title="일일 퀘스트" subtitle="오늘도 작은 한 걸음 🌱"/><div className="day-tabs"><b>오늘</b><span>이번 주</span></div><section className="quest-panel">{quests.map(q=><button key={q.id} className={todayCompleted[q.id]?'done':''} onClick={()=>toggleQuest(q.id)}><em>{todayCompleted[q.id]?'✓':''}</em><i>{q.icon||'🌱'}</i><span><b>{q.title}</b><small>{q.category} · +{q.xp} XP</small></span></button>)}</section><button className="primary" onClick={addQuest}>＋ 퀘스트 추가하기</button></main>}
function Pace({now,stats,history,quests,totalXP}){const days=Array.from({length:7},(_,i)=>addDays(now,-6+i));return <main className="page"><PageHead title="나의 기록" subtitle="이번 주도 너무 잘하고 있어요! 🧡"/><section className="record-banner"><div><b>꾸준한 게 제일 멋져!</b><p>완벽보다 다시 돌아오는 하루가 중요해요.</p></div><Mascot small/></section><section className="weekly-bars">{days.map(d=>{const r=history[localDateKey(d)],n=r?quests.filter(q=>r.completed?.[q.id]).length:0,p=Math.round(n/quests.length*100);return <div key={localDateKey(d)}><span><i style={{height:`${Math.max(8,p)}%`}}/></span><small>{['일','월','화','수','목','금','토'][d.getDay()]}</small></div>})}</section><section className="record-list"><div><span>🔥</span><p>최근 Pace Score</p><b>{stats.score}점</b></div><div><span>👑</span><p>누적 XP</p><b>{totalXP} XP</b></div><div><span>🌿</span><p>완료한 퀘스트</p><b>{Object.values(history).reduce((a,r)=>a+quests.filter(q=>r.completed?.[q.id]).length,0)}개</b></div></section></main>}
function Special({special,specialDone,toggleSpecial}){return <main className="page"><PageHead title="스페셜 퀘스트" subtitle="지금, 조금 더 특별한 도전을 해볼까요?"/><section className="special-land"><div className="mountain m1"/><div className="mountain m2"/><span>🏁</span><p>내 페이스로 한 걸음 더!</p></section><section className="special-cards"><article><i>🏋️</i><div><b>한 달 꾸준히 운동하기</b><small>30일 챌린지</small></div><em>›</em></article><article><i>📚</i><div><b>책 한 권 완독하기</b><small>지식 레벨 업!</small></div><em>›</em></article><article><i>{special.icon}</i><div><b>{special.title}</b><small>{special.description}</small></div><button onClick={toggleSpecial}>{specialDone?'✓':'›'}</button></article><article><i>📵</i><div><b>일주일 SNS 쉬기</b><small>디지털 디톡스</small></div><em>›</em></article></section></main>}
function Profile({quests,addQuest,removeQuest,totalXP,level}){return <main className="page"><PageHead title="마이 페이지"/><section className="profile-hero"><div className="profile-mascot"><Mascot/></div><h2>My Pace</h2><p>조금씩, 꾸준히, 나답게 🌱</p></section><section className="profile-menu"><button><span>👤</span><b>내 정보</b><em>›</em></button><button><span>🔔</span><b>알림 설정</b><em>›</em></button><button><span>🌙</span><b>테마 모드</b><em>라이트 ›</em></button><button onClick={addQuest}><span>➕</span><b>퀘스트 추가</b><em>›</em></button><button><span>🏆</span><b>Lv.{level} · {totalXP} XP</b><em>›</em></button></section><section className="manage">{quests.map(q=><button key={q.id} onClick={()=>removeQuest(q.id)}>{q.title}<span>×</span></button>)}</section></main>}
function PageHead({title,subtitle}){return <header className="page-head"><Logo/><h1>{title}</h1>{subtitle&&<p>{subtitle}</p>}</header>}
function Nav({tab,setTab}){return <nav className="bottom-nav">{[['today','⌂','홈'],['quests','▣','퀘스트'],['pace','▥','통계'],['special','☆','스페셜'],['profile','♙','마이']].map(([id,icon,label])=><button key={id} className={tab===id?'active':''} onClick={()=>setTab(id)}><span>{icon}</span><small>{label}</small></button>)}</nav>}
export default App
