import { useEffect, useMemo, useState } from 'react'
import './App.css'

const DEFAULT_QUESTS = [
  { id: 'tidy', title: '내 몫 정리', category: 'LIFE', xp: 10 },
  { id: 'workout', title: '운동하기', category: 'BODY', xp: 10 },
  { id: 'english', title: '영어 공부 10분 이상', category: 'GROWTH', xp: 10 },
  { id: 'reading', title: '독서하기 5페이지 이상', category: 'GROWTH', xp: 10 },
  { id: 'house', title: '집안일 오늘 하나는 꼭', category: 'LIFE', xp: 10 },
]
const SPECIALS = [
  { id: 'dust', title: '숨어있는 먼지를 찾아라', description: '평소 잘 닦지 않는 곳 한 군데의 먼지를 닦아보세요.', xp: 20 },
  { id: 'reset', title: '10분 리셋', description: '타이머 10분을 켜고 눈에 보이는 공간 하나를 정리해보세요.', xp: 20 },
  { id: 'walk', title: '한 정거장 더', description: '오늘은 평소보다 15분 더 걸어보세요.', xp: 20 },
  { id: 'message', title: '마음 한 줄 보내기', description: '고마운 사람에게 짧은 안부나 감사 메시지를 보내보세요.', xp: 20 },
]
const CATEGORIES = ['LIFE', 'BODY', 'GROWTH', 'RELATIONSHIP', 'WORK', 'HOBBY']
const localDateKey = (d = new Date()) => { const y=d.getFullYear(); const m=String(d.getMonth()+1).padStart(2,'0'); const day=String(d.getDate()).padStart(2,'0'); return `${y}-${m}-${day}` }
const addDays = (d,n) => { const x=new Date(d); x.setDate(x.getDate()+n); return x }
const weekKey = (d=new Date()) => { const x=new Date(d); const day=(x.getDay()+6)%7; x.setDate(x.getDate()-day); return localDateKey(x) }
const safeParse = (value,fallback) => { try { return value ? JSON.parse(value) : fallback } catch { return fallback } }

function App() {
  const [now,setNow]=useState(new Date()); const todayKey=localDateKey(now); const thisWeek=weekKey(now)
  const [tab,setTab]=useState('today')
  const [dark,setDark]=useState(()=>localStorage.getItem('myPaceDark')==='true')
  const [quests,setQuests]=useState(()=>safeParse(localStorage.getItem('myPaceQuestDefinitions'),DEFAULT_QUESTS))
  const [history,setHistory]=useState(()=>{ const saved=safeParse(localStorage.getItem('myPaceHistory'),{}); if(Object.keys(saved).length)return saved; const legacy=safeParse(localStorage.getItem('myPaceQuests'),null); if(!legacy)return {}; return {[localDateKey()]:{completed:Object.fromEntries(legacy.map(q=>[q.id,!!q.completed]))}} })
  const [specialHistory,setSpecialHistory]=useState(()=>safeParse(localStorage.getItem('myPaceSpecialHistory'),{}))
  useEffect(()=>{const id=setInterval(()=>setNow(new Date()),60000);return()=>clearInterval(id)},[])
  useEffect(()=>localStorage.setItem('myPaceHistory',JSON.stringify(history)),[history])
  useEffect(()=>localStorage.setItem('myPaceSpecialHistory',JSON.stringify(specialHistory)),[specialHistory])
  useEffect(()=>localStorage.setItem('myPaceQuestDefinitions',JSON.stringify(quests)),[quests])
  useEffect(()=>{localStorage.setItem('myPaceDark',dark);document.documentElement.dataset.theme=dark?'dark':'light'},[dark])
  const todayCompleted=history[todayKey]?.completed||{}; const completedCount=quests.filter(q=>todayCompleted[q.id]).length
  const special=SPECIALS[Math.abs([...thisWeek].reduce((a,c)=>a+c.charCodeAt(0),0))%SPECIALS.length]; const specialDone=specialHistory[thisWeek]?.completed===true
  const stats=useMemo(()=>{const days=Array.from({length:28},(_,i)=>localDateKey(addDays(now,-27+i)));let scheduled=0,done=0;const category=Object.fromEntries(CATEGORIES.map(c=>[c,{done:0,total:0}]));days.forEach(key=>{const rec=history[key];if(!rec)return;quests.forEach(q=>{scheduled++;category[q.category].total++;if(rec.completed?.[q.id]){done++;category[q.category].done++}})});const score=scheduled?Math.round(done/scheduled*100):Math.round(completedCount/Math.max(quests.length,1)*100);return{score,category,days}},[history,quests,now,completedCount])
  const totalXP=useMemo(()=>{let xp=720;Object.values(history).forEach(rec=>quests.forEach(q=>{if(rec.completed?.[q.id])xp+=q.xp||10}));Object.values(specialHistory).forEach(rec=>{if(rec.completed)xp+=rec.xp||20});return xp},[history,quests,specialHistory])
  const level=Math.floor(totalXP/100), levelXP=totalXP%100; const levelNames=['Starting Out','Finding Rhythm','Showing Up','Steady Pace','In My Flow']; const levelName=levelNames[Math.min(Math.floor(level/3),levelNames.length-1)]
  const toggleQuest=id=>setHistory(prev=>({...prev,[todayKey]:{...(prev[todayKey]||{}),completed:{...(prev[todayKey]?.completed||{}),[id]:!todayCompleted[id]}}}))
  const toggleSpecial=()=>setSpecialHistory(prev=>({...prev,[thisWeek]:{completed:!specialDone,xp:special.xp,id:special.id}}))
  const greeting=now.getHours()<12?'좋은 아침이에요':now.getHours()<18?'좋은 오후예요':'좋은 저녁이에요'; const formattedDate=`${now.getMonth()+1}월 ${now.getDate()}일 · ${['일요일','월요일','화요일','수요일','목요일','금요일','토요일'][now.getDay()]}`
  const addQuest=()=>{if(quests.length>=5)return alert('Daily Quest는 최대 5개까지 설정할 수 있어요.');const title=prompt('새 Daily Quest 이름을 입력하세요.');if(!title?.trim())return;const category=prompt(`카테고리를 입력하세요: ${CATEGORIES.join(', ')}`,'LIFE')?.toUpperCase();setQuests(prev=>[...prev,{id:`q-${Date.now()}`,title:title.trim(),category:CATEGORIES.includes(category)?category:'LIFE',xp:10}])}
  const removeQuest=id=>{if(quests.length<=3)return alert('Daily Quest는 최소 3개가 필요해요.');setQuests(prev=>prev.filter(q=>q.id!==id))}
  return <div className="app-shell"><div className="phone-frame">
    {tab==='today'&&<TodayView {...{greeting,formattedDate,stats,level,levelName,levelXP,quests,todayCompleted,completedCount,toggleQuest,special,specialDone,toggleSpecial}}/>}
    {tab==='pace'&&<PaceView stats={stats} history={history} quests={quests} now={now}/>} {tab==='profile'&&<ProfileView dark={dark} setDark={setDark} quests={quests} addQuest={addQuest} removeQuest={removeQuest} totalXP={totalXP} level={level}/>}<nav className="bottom-nav"><NavButton active={tab==='today'} icon="⌂" label="Today" onClick={()=>setTab('today')}/><NavButton active={tab==='pace'} icon="◔" label="Pace" onClick={()=>setTab('pace')}/><NavButton active={tab==='profile'} icon="○" label="Profile" onClick={()=>setTab('profile')}/></nav></div></div>
}
function TodayView({greeting,formattedDate,stats,level,levelName,levelXP,quests,todayCompleted,completedCount,toggleQuest,special,specialDone,toggleSpecial}){const label=stats.score>=80?'GREAT PACE':stats.score>=60?'GOOD PACE':stats.score>=40?'FINDING PACE':'STARTING';return <main className="page today-page"><header className="hero"><div><p className="eyebrow">{formattedDate}</p><h1>{greeting}, 승호님!</h1><p>완벽하지 않아도 괜찮아요. 오늘도 내 페이스로.</p></div><div className="buddy"><span>✦</span><b>◡</b></div></header><section className="score-card card"><div className="score-ring" style={{'--score':`${stats.score*3.6}deg`}}><div><strong>{stats.score}</strong><span>{label}</span></div></div><div className="score-copy"><span className="kicker">PACE SCORE</span><h2>{stats.score>=70?'꾸준히 해내고 있어요!':'천천히 리듬을 만들고 있어요'}</h2><p>최근 28일의 Daily Quest 기록을 반영해요.</p></div></section><section className="level-card card"><div className="level-row"><div><span className="kicker">LEVEL {level}</span><h2>Lv.{level} · {levelName}</h2></div><strong>{levelXP} / 100 XP</strong></div><div className="progress"><span style={{width:`${levelXP}%`}}/></div><p>다음 레벨까지 {100-levelXP} XP · 실패해도 XP는 줄지 않아요.</p></section><section className="section"><div className="section-title"><div><span className="kicker">DAILY</span><h2>Today's Quest</h2></div><span className="count-pill">{completedCount}/{quests.length}</span></div><div className="quest-list">{quests.map(q=><button className={`quest ${todayCompleted[q.id]?'done':''}`} key={q.id} onClick={()=>toggleQuest(q.id)}><span className="check">{todayCompleted[q.id]?'✓':''}</span><span className="quest-copy"><b>{q.title}</b><small>{q.category}</small></span><span className="xp">+{q.xp} XP</span></button>)}</div></section><section className={`special card ${specialDone?'done':''}`}><div className="special-head"><span className="special-badge">WEEKLY SPECIAL</span><b>+{special.xp} XP</b></div><h2>{special.title}</h2><p>{special.description}</p><div className="special-foot"><span>이번 주까지 · Pace Score에는 미반영</span><button onClick={toggleSpecial}>{specialDone?'완료 ✓':'완료하기'}</button></div></section><p className="motto">A little better, every day.</p></main>}
function PaceView({stats,history,quests,now}){const rows=CATEGORIES.map(name=>{const x=stats.category[name];return{name,score:x.total?Math.round(x.done/x.total*100):0,active:x.total>0}});const last14=Array.from({length:14},(_,i)=>addDays(now,-13+i));return <main className="page"><header className="simple-header"><span className="kicker">MY RHYTHM</span><h1>Pace</h1><p>연속 기록보다, 최근의 흐름을 봐요.</p></header><section className="pace-hero card"><div><span className="kicker">LAST 28 DAYS</span><strong>{stats.score}</strong><p>Pace Score</p></div><div className="mini-copy"><b>{stats.score>=70?'좋은 흐름이에요':'다시 시작하기 좋은 순간이에요'}</b><span>빠진 날이 있어도 점수는 다시 올라옵니다.</span></div></section><section className="section"><div className="section-title"><div><span className="kicker">RECENT</span><h2>최근 14일</h2></div></div><div className="heatmap">{last14.map(d=>{const k=localDateKey(d),rec=history[k],done=rec?quests.filter(q=>rec.completed?.[q.id]).length:0,ratio=rec?done/quests.length:0;return <div key={k} className="heat-day"><span className={`heat-dot h${Math.ceil(ratio*4)}`}></span><small>{d.getDate()}</small></div>})}</div></section><section className="section"><div className="section-title"><div><span className="kicker">BALANCE</span><h2>카테고리별 Pace</h2></div></div><div className="category-list">{rows.map(c=><div className="category-row" key={c.name}><div><b>{c.name}</b><span>{c.active?`${c.score}%`:'기록 없음'}</span></div><div className="thin-progress"><span style={{width:`${c.score}%`}}/></div></div>)}</div></section><section className="insight card"><span>✦</span><div><b>이번 리포트의 한마디</b><p>완벽한 일주일보다 다시 돌아오는 하루가 더 중요해요.</p></div></section></main>}
function ProfileView({dark,setDark,quests,addQuest,removeQuest,totalXP,level}){return <main className="page"><header className="simple-header"><span className="kicker">MY PACE</span><h1>Profile</h1><p>나에게 맞는 속도로 앱을 조정해요.</p></header><section className="profile-card card"><div className="avatar">승</div><div><h2>승호</h2><p>Lv.{level} · Total {totalXP.toLocaleString()} XP</p></div></section><section className="section"><div className="section-title"><div><span className="kicker">ROUTINE</span><h2>Daily Quest 설정</h2></div><button className="text-button" onClick={addQuest}>+ 추가</button></div><div className="settings-list">{quests.map(q=><div className="setting-row" key={q.id}><div><b>{q.title}</b><span>{q.category} · +{q.xp} XP</span></div><button onClick={()=>removeQuest(q.id)}>×</button></div>)}</div><p className="helper">Daily Quest는 3~5개를 추천해요. 부담보다 지속 가능성을 우선합니다.</p></section><section className="section"><div className="section-title"><div><span className="kicker">APPEARANCE</span><h2>화면 설정</h2></div></div><button className="toggle-row card" onClick={()=>setDark(!dark)}><div><b>다크 모드</b><span>편한 화면으로 바꿔보세요.</span></div><span className={`switch ${dark?'on':''}`}><i/></span></button></section><section className="about card"><span className="app-mark">M</span><div><b>My Pace v1.0</b><p>완벽하지 않아도 괜찮아. 내 페이스로, 조금씩.</p></div></section></main>}
function NavButton({active,icon,label,onClick}){return <button className={active?'active':''} onClick={onClick}><span>{icon}</span><small>{label}</small></button>}
export default App
